name: document_uploader
description: Plugin for upload documents asynchronously
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  image: ^4.5.4
  uuid: ^4.5.1
  logger: ^2.6.1
  get_it: ^8.2.0
  hive: ^2.2.3
  json_annotation: ^4.9.0
  collection: ^1.19.1
  geolocator:
    git:
      url: https://github.com/eb-so/flutter-geolocator
      ref: main
      path: geolocator
  path_provider: ^2.1.5
  crypto: ^3.0.6
  http: ^1.5.0
  core:
    path: ../core/
  meta: ^1.16.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  mockito: ^5.4.4

