name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  http: ^1.5.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.1
  get_it: ^7.7.0
  logger: ^1.4.0
  geolocator:
    git:
      url: https://github.com/eb-so/flutter-geolocator
      ref: main
      path: geolocator
  json_annotation: ^4.9.0
  stacked_services: ^1.6.0
  hive: ^2.2.3
  intl: ^0.20.2
  stacked: ^3.4.3
  mask_text_input_formatter: ^2.9.0
  rive: ^0.12.4
  flex_color_scheme: ^8.3.0
  sentry_flutter: ^8.14.2
  collection: ^1.19.1
  permission_handler: ^11.4.0
  skeletonizer: ^2.1.0+1
  url_launcher: ^6.3.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
flutter:
  assets:
    - assets/certificates/
    - assets/rive/
