name: the_bat_mobile
description: The Booth-Agent-Teller mobile app
publish_to: "none" # Do not remove this line
version: 3.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  # Local packages
  core:
    path: ../core/
  document_uploader:
    path: ../docUp/
  # Custom packages
  openidconnect:
    git:
      url: https://github.com/eb-so/openidconnect_flutter
      ref: main
      path: openidconnect
  feedback:
    git:
      url: https://github.com/eb-so/feedback.git
      ref: master
      path: feedback
  geolocator:
    git:
      url: https://github.com/eb-so/flutter-geolocator
      ref: main
      path: geolocator
  cupertino_icons: ^1.0.8
  camera: ^0.11.2
  url_launcher: ^6.3.2
  dots_indicator: ^4.0.1
  smooth_page_indicator: ^1.2.1
  plugin_platform_interface: ^2.1.8
  camera_platform_interface: ^2.10.0
  flutter_markdown: ^0.7.7+1
  crypto: ^3.0.6
  sentry_flutter: ^9.6.0
  sentry_hive: ^9.6.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  device_info_plus: ^12.0.0
  package_info_plus: ^9.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  recase: ^4.1.0
  collection: ^1.19.1
  http: ^1.5.0
  uuid: ^4.5.1
  blinkid_flutter: ^7.4.0
  flex_color_scheme: ^8.3.0
  image: ^4.5.4
  stacked: ^3.5.0
  stacked_services: ^1.6.0
  get_it: ^8.2.0
  clock: ^1.1.2
  flutter_svg: ^2.2.1
  provider: ^6.1.5+1
  firebase_core: ^4.1.0
  firebase_core_platform_interface: ^6.0.0
  firebase_analytics: ^12.0.1
  mask_text_input_formatter: ^2.9.0
  root_jailbreak_sniffer: ^1.1.1
  auto_size_text: ^3.0.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  showcaseview: ^4.0.1
  connectivity_plus: ^7.0.0
  number_text_input_formatter: ^1.0.0+8
  firebase_performance: ^0.11.0+1
  flutter_animate: ^4.5.2
  expansion_tile_card: ^3.0.0
  convert: ^3.1.2
  syncfusion_flutter_charts: ^31.1.18
  pin_code_fields: ^8.0.1
  webview_cookie_manager: ^2.0.6
  flutter_sticky_header: ^0.8.0
  open_file: ^3.5.10
  permission_handler: ^12.0.1
  animated_loading_border: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  sentry_dart_plugin: ^3.1.1

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  stacked_generator: ^2.0.0-pre.1
  patrol: ^3.19.0

patrol:
  app_name: BAT
  android:
    package_name: com.mukuru.staffapp
  ios:
    bundle_id: com.mukuru.staffapp

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project: bat-app
  org: mukuru
  log_level: error # possible values: trace, debug, info, warn, error
  ignore_missing: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svgs/
    - assets/images/country_flag/
    - integration_test/helpers/bw.json
    - integration_test/check_rates/cash_collections/check_rate_helpers/check_rates_cash_collection_countries.json
    - integration_test/check_rates/cash_collections/check_rate_helpers/check_rates_all_countries.json
    - test/helpers/test_assets/
    - test/helpers/test_assets/customers/

  fonts:
    - family: Madera
      fonts:
        - asset: assets/fonts/madera/Monotype - Madera ExtraBold.otf
          weight: 800
        - asset: assets/fonts/madera/Monotype - Madera ExtraBold Italic.otf
          style: italic
          weight: 800
        - asset: assets/fonts/madera/Monotype - Madera Bold.otf
          weight: 700
        - asset: assets/fonts/madera/Monotype - Madera Bold Italic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/madera/Monotype - Madera Medium.otf
          weight: 500
        - asset: assets/fonts/madera/Monotype - Madera Medium.otf
          style: italic
          weight: 500
        - asset: assets/fonts/madera/Monotype - Madera Regular.otf
          weight: 400
        - asset: assets/fonts/madera/Monotype - Madera Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/madera/Monotype - Madera Light.otf
          weight: 300
        - asset: assets/fonts/madera/Monotype - Madera Light Italic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/madera/Monotype - Madera Thin.otf
          weight: 200
        - asset: assets/fonts/madera/Monotype - Madera Thin.otf
          style: italic
          weight: 200
        - asset: assets/fonts/madera/Monotype - Madera UltraLight.otf
          weight: 100
        - asset: assets/fonts/madera/Monotype - Madera UltraLight Italic.otf
          style: italic
          weight: 100
